<a href="https://colab.research.google.com/github/0518M/Numpy_Pandas/blob/main/Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np
a = np.array([1, 2, 3])  
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5               
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,9,3],[3,5,6]])   
print(b)

[[1 9 3]
 [3 5 6]]


In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 9 3


In [ ]:
a = np.zeros((2,2))  
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))  
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)       
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) 
print(e)

[[0.20545777 0.23675243]
 [0.61641855 0.53315815]]


Array Indexing

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

77
77


In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a.shape)

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

(3, 2)
[1 4 5]
[1 4 5]


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])
print(b)

# Select one element from each row of a using the indices in b
#print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"
print(a[:, b])

[0 2 0 1]
[[ 1  3  1  2]
 [ 4  6  4  5]
 [ 7  9  7  8]
 [10 12 10 11]]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Booolean indexing

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2) 

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
print(a[bool_idx])
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


Datatypes

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


Array math functions

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:

print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:

print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:

print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[2,2],[6,4]])
y = np.array([[9,6],[5,8]])

v = np.array([9,10])
w = np.array([19, 12])
print(v.shape, w.shape)
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

print(x.dot(y))


(2,) (2,)
291
291
[[28 28]
 [74 68]]


In [ ]:
z = np.eye(2)
print(x.dot(z))

[[2. 2.]
 [6. 4.]]


In [ ]:
print(v @ w) #@ equal to numpy dot operator

291


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[38 94]
[38 94]
[38 94]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[28 28]
 [74 68]]
[[28 28]
 [74 68]]
[[28 28]
 [74 68]]


In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"


10


In [ ]:
print(x)
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]
[4 6]
[3 7]


In [ ]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v.shape)
print(v )
print("transpose\n", v.T)

(1, 3)
[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


Pandas

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series([1,2,3,4])
print(s1)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:

fruits = np.array(['apple','orange','mango','pear'])
series2 = pd.Series(fruits)
print(series2)


0     apple
1    orange
2     mango
3      pear
dtype: object


In [ ]:
df1 = pd.DataFrame({
    "C1": [1, 4, 8, 7, 9],
    "C2": ['a', 'column', 'with', 'a', 'string'],
    "C3": [1.23, 23.5, 45.6, 32.1234, 89.453],
    "C4": [True, False, True, False, True]
})


In [ ]:
# It is possible for us to create a DataFrame from a list or even a set of lists.
mylist = [4, 8, 12, 16, 20]
df2 = pd.DataFrame(mylist)
print(df2)

    0
0   4
1   8
2  12
3  16
4  20


In [ ]:
items = [['Phone', 2000], ['TV', 1500], ['Radio', 800]]
df3 = pd.DataFrame(items)
print(df3)

       0     1
0  Phone  2000
1     TV  1500
2  Radio   800


In [ ]:
items = [['Phone', 2000], ['TV', 1500], ['Radio', 800]]
df4 = pd.DataFrame(items, columns=['Item', 'Price'], dtype=float)
print(df4)

    Item   Price
0  Phone  2000.0
1     TV  1500.0
2  Radio   800.0


<ipython-input-42-0755eeebd180>:2: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df4 = pd.DataFrame(items, columns=['Item', 'Price'], dtype=float)


In [ ]:
# To get a summary of this item's data
df4.describe()

Price
count     3.000000
mean   1433.333333
std     602.771377
min     800.000000
25%    1150.000000
50%    1500.000000
75%    1750.000000
max    2000.000000

In [ ]:
# Merging
d1 = {
    'subject_id': ['1', '2', '3', '4', '5'],
    'student_name': ['John', 'Emily', 'Kate', 'Joseph', 'Dennis']
}

d2 = {
    'subject_id': ['4', '5', '6', '7', '8'],
    'student_name': ['Brian', 'William', 'Lilian', 'Grace', 'Caleb']
}

df1 = pd.DataFrame(d1, columns=['subject_id', 'student_name'])
df2 = pd.DataFrame(d2, columns=['subject_id', 'student_name'])
df1

subject_id student_name
0          1         John
1          2        Emily
2          3         Kate
3          4       Joseph
4          5       Dennis

In [ ]:
df2

subject_id student_name
0          4        Brian
1          5      William
2          6       Lilian
3          7        Grace
4          8        Caleb

In [ ]:
pd.merge(df1, df2, on='subject_id')

subject_id student_name_x student_name_y
0          4         Joseph          Brian
1          5         Dennis        William

In [ ]:
# Grouping
#  process of putting data into various categories.

raw = {
    'Name': ['John', 'John', 'Grace', 'Grace', 'Benjamin', 'Benjamin', 'Benjamin',
        'Benjamin', 'John', 'Alex', 'Alex', 'Alex'],
    'Position': [2, 1, 1, 4, 2, 4, 3, 1, 3, 2, 4, 3],
    'Year': [2009, 2010, 2009, 2010, 2010, 2010, 2011, 2012, 2011, 2013, 2013, 2012],
    'Marks':[408, 398, 422, 376, 401, 380, 396, 388, 356, 402, 368, 378]
}
df3 = pd.DataFrame(raw)
df3

Name  Position  Year  Marks
0       John         2  2009    408
1       John         1  2010    398
2      Grace         1  2009    422
3      Grace         4  2010    376
4   Benjamin         2  2010    401
5   Benjamin         4  2010    380
6   Benjamin         3  2011    396
7   Benjamin         1  2012    388
8       John         3  2011    356
9       Alex         2  2013    402
10      Alex         4  2013    368
11      Alex         3  2012    378

In [ ]:
group = df3.groupby('Year')
group
group.get_group(2010)

Name  Position  Year  Marks
1      John         1  2010    398
3     Grace         4  2010    376
4  Benjamin         2  2010    401
5  Benjamin         4  2010    380

In [ ]:

print(pd.concat([df1, df2]))


  subject_id student_name
0          1         John
1          2        Emily
2          3         Kate
3          4       Joseph
4          5       Dennis
0          4        Brian
1          5      William
2          6       Lilian
3          7        Grace
4          8        Caleb


In [ ]:
pd.concat([df1, df2], axis=1)

subject_id student_name subject_id student_name
0          1         John          4        Brian
1          2        Emily          5      William
2          3         Kate          6       Lilian
3          4       Joseph          7        Grace
4          5       Dennis          8        Caleb

In [ ]:
data = {
    'Name': ['John', 'Alice', 'Joseph', 'Alex'],
    'English': [64, 78, 68, 58],
    'Maths': [76, 54, 72, 64]
}

df = pd.DataFrame(data)
df.describe()

English      Maths
count   4.000000   4.000000
mean   67.000000  66.500000
std     8.406347   9.712535
min    58.000000  54.000000
25%    62.500000  61.500000
50%    66.000000  68.000000
75%    70.500000  73.000000
max    78.000000  76.000000